### ISSUE TITLE
FindNodeModuleImport by npm convention

### ISSUE THREAD

**Issue by razronen** [alexandrudima/monaco-plugin-helpers#1]
Hi, 

I want to use monaco-plugin-helpers to prepublish the npm package monaco-kusto.

For that, I need packageESM.ts - findNodeModuleImport function to be able to load 3rd party libraries by npm convention:
https://docs.npmjs.com/about-packages-and-modules#about-modules

Basiclly:
A folder with a package.json file containing a "main" field.
A folder with an index.js file in it.

Currently trying to load lodash and xregexp which are failing.

This is probably a 1-liner PR, I'll be happy to do it.

**Comment by alexdima** [comment]
Done via #2
